import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import Header from "./Components/Header";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body
        className={`${inter.variable} ${oswald.variable} min-h-full flex flex-col bg-[#0C0E11]`}
      >
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
