import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Header from "./Components/Header";
import ExerciseContext from "./Context/ExerciseContext";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body
        className={`${inter.variable} ${oswald.variable} min-h-full flex flex-col bg-[#0C0E11]`}
      >
        <ExerciseContext>
          <ToastContainer />
          <Header />
          <div>{children}</div>
        </ExerciseContext>
      </body>
    </html>
  );
}
